name: Auto Update Remote Rules

on:
  schedule:
    - cron: '30 9 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout remote_rules
        uses: actions/checkout@v4
        with:
          ref: remote_rules

      - name: make directory
        run: mkdir -p rules

      - name: clear rules directory
        run: rm -rf rules/* && mkdir -p rules

      - name: download
        run: |

          curl -sL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Cloudflare/Cloudflare_No_Resolve.yaml -o rules/Cloudflare.yaml

          curl -sL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube_No_Resolve.yaml -o rules/YouTube.yaml

          curl -sL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub_No_Resolve.yaml -o rules/GitHub.yaml

          curl -sL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Steam/Steam_No_Resolve.yaml -o rules/Steam.yaml

          curl -sL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/SteamCN/SteamCN_No_Resolve.yaml -o rules/SteamCN.yaml

          curl -sL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google_No_Resolve.yaml -o rules/Google.yaml

          curl -sL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Game/Roblox/Roblox_No_Resolve.yaml -o rules/Roblox.yaml

          curl -sL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI_No_Resolve.yaml -o rules/OpenAI.yaml

          curl -sL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TikTok/TikTok_No_Resolve.yaml -o rules/TikTok.yaml

          curl -sL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Spotify/Spotify_No_Resolve.yaml -o rules/Spotify.yaml

          curl -sL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Discord/Discord_No_Resolve.yaml -o rules/Discord.yaml

          curl -sL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan_No_Resolve.yaml -o rules/Lan.yaml

          curl -sL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft_No_Resolve.yaml -o rules/Microsoft.yaml

          curl -sL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram_No_Resolve.yaml -o rules/Telegram.yaml

          curl -sL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PikPak/PikPak_No_Resolve.yaml -o rules/PikPak.yaml

          curl -sL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GlobalMedia/GlobalMedia_Classical_No_Resolve.yaml -o rules/GlobalMedia.yaml

          curl -sL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple_Classical_No_Resolve.yaml -o rules/Apple.yaml

          curl -sL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix_Classical_No_Resolve.yaml -o rules/Netflix.yaml

      - name: global config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: commit
        id: commit
        run: |
          git add rules/
          if git diff --cached --quiet; then
            echo "No changes to commit"
            echo "changed=false" >> "$GITHUB_OUTPUT"
          else
            git commit -m "auto: update rules"
            git push origin remote_rules
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: overwrite master
        if: steps.commit.outputs.changed == 'true'
        run: |
          git fetch origin
          git checkout master
          git checkout origin/remote_rules -- rules/
          git add -A
          git commit -m "auto: overwrite master with remote_rules"
          git push origin master
      
      
      
      
      
      
